version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - host-network
    environment:
      # Add environment variables as needed
      VARIABLE_NAME: value
      ANOTHER_VARIABLE: another_value

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - host-network
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      # Add other environment variables as needed
      - ANOTHER_VARIABLE=another_value

  database:
    image: mysql:latest
    networks:
      - host-network
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d

  cache:
    image: redis:latest
    networks:
      - host-network
    environment:
      # Add environment variables as needed
      VARIABLE_NAME: value
      ANOTHER_VARIABLE: another_value

  shared:
    build:
      context: ./shared
      dockerfile: Dockerfile
    networks:
      - host-network
    environment:
      # Add environment variables as needed
      VARIABLE_NAME: value
      ANOTHER_VARIABLE: another_value

networks:
  host-network:
    driver: bridge
