version: '3'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    networks:
      - host-network
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      # other environment variables as needed

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    networks:
      - host-network
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      # other environment variables as needed

  # other services as needed

networks:
  host-network:
    driver: bridge